services:
  loki:
    image: grafana/loki:latest
    container_name: wishlists-loki
    restart: unless-stopped
    volumes:
      - ./configs/loki-config.yml:/etc/loki/local-config.yaml
      - .data/.loki_data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - backend_network

  alloy:
    image: grafana/alloy:latest
    container_name: wishlists-alloy
    restart: unless-stopped
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
    environment:
      ALLOY_DEPLOY_MODE: docker
    volumes:
      - ./configs/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro # Needed for Docker container discovery
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki
    networks:
      - backend_network

  grafana:
    image: grafana/grafana:latest
    container_name: wishlists-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - backend_network


  db:
    container_name: wishlists-db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: "wishlists"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"
    ports:
      - "5432:5432"
    volumes:
      - "${POSTGRES_DATA_FOLDER}:/var/lib/postgresql/data"
    networks:
      - backend_network


  backend:
    container_name: wishlists-backend
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      PG_DSN: "postgresql://postgres:postgres@wishlists-db:5432/wishlists"
      PORT: "${BACKEND_PORT}"
    depends_on:
      - db
    networks:
      - backend_network

volumes:
  grafana-storage:
  loki-storage:

networks:
  backend_network:
