services:
  alloy:
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"

  grafana:
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  db:
    ports:
      - "5432:5432"

  backend:
    environment:
      TLS_CERT_FILE: "/cert.pem"
      TLS_KEY_FILE: "/key.pem"
    volumes:
      - "${TLS_CERT_FILE}:/cert.pem:ro"
      - "${TLS_KEY_FILE}:/key.pem:ro"