services:
  grafana:
    ports:
      - "33005:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin123
      GF_SECURITY_ADMIN_PASSWORD: sdkfvjb3489gf
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SERVER_CERT_KEY: /etc/grafana/grafana.key
      GF_SERVER_CERT_FILE: /etc/grafana/grafana.crt
      GF_SERVER_PROTOCOL: https
    volumes:
      - "${TLS_CERT_FILE}:/etc/grafana/grafana.crt:ro"
      - "${TLS_KEY_FILE}:/etc/grafana/grafana.key:ro"

  backend:
    environment:
      TLS_CERT_FILE: "/cert.pem"
      TLS_KEY_FILE: "/key.pem"
    volumes:
      - "${TLS_CERT_FILE}:/cert.pem:ro"
      - "${TLS_KEY_FILE}:/key.pem:ro"
