// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Friend struct {
	UserID   int64 `json:"user_id"`
	FriendID int64 `json:"friend_id"`
}

type FriendsRequest struct {
	UserIDFrom int64 `json:"user_id_from"`
	UserIDTo   int64 `json:"user_id_to"`
}

type User struct {
	ID       int64       `json:"id"`
	Username pgtype.Text `json:"username"`
	PhotoUrl pgtype.Text `json:"photo_url"`
}

type Wish struct {
	ID          int64       `json:"id"`
	OwnerID     int64       `json:"owner_id"`
	ListID      int64       `json:"list_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Price       string      `json:"price"`
	Links       []byte      `json:"links"`
	Reservable  bool        `json:"reservable"`
	ReservedBy  pgtype.Int8 `json:"reserved_by"`
}

type Wishlist struct {
	ID          int64  `json:"id"`
	OwnerID     int64  `json:"owner_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	IsPrivate   bool   `json:"is_private"`
}

type WishlistsAccessList struct {
	ListID int64 `json:"list_id"`
	UserID int64 `json:"user_id"`
}
