// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
)

const createFriendsRelationship = `-- name: CreateFriendsRelationship :exec
INSERT INTO friends (user_id, friend_id)
VALUES ($1, $2), ($2, $1)
`

type CreateFriendsRelationshipParams struct {
	UserID   int64 `json:"user_id"`
	FriendID int64 `json:"friend_id"`
}

func (q *Queries) CreateFriendsRelationship(ctx context.Context, arg CreateFriendsRelationshipParams) error {
	_, err := q.db.Exec(ctx, createFriendsRelationship, arg.UserID, arg.FriendID)
	return err
}

const createFriendsRequest = `-- name: CreateFriendsRequest :exec
INSERT INTO friends_requests (user_id_from, user_id_to)
VALUES ($1, $2)
`

type CreateFriendsRequestParams struct {
	UserIDFrom int64 `json:"user_id_from"`
	UserIDTo   int64 `json:"user_id_to"`
}

func (q *Queries) CreateFriendsRequest(ctx context.Context, arg CreateFriendsRequestParams) error {
	_, err := q.db.Exec(ctx, createFriendsRequest, arg.UserIDFrom, arg.UserIDTo)
	return err
}

const createWishlist = `-- name: CreateWishlist :one
INSERT INTO wishlists (owner_id, title, description, is_private)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, title, description, is_private
`

type CreateWishlistParams struct {
	OwnerID     int64  `json:"owner_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	IsPrivate   bool   `json:"is_private"`
}

func (q *Queries) CreateWishlist(ctx context.Context, arg CreateWishlistParams) (Wishlist, error) {
	row := q.db.QueryRow(ctx, createWishlist,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.IsPrivate,
	)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.IsPrivate,
	)
	return i, err
}

const getFriends = `-- name: GetFriends :many
SELECT id, username, photo_url
FROM users
WHERE id IN (SELECT friend_id FROM friends WHERE user_id = $1)
`

func (q *Queries) GetFriends(ctx context.Context, userID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, getFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Username, &i.PhotoUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncomingFriendsRequests = `-- name: GetIncomingFriendsRequests :many
SELECT id, username, photo_url
FROM users
WHERE id IN (SELECT user_id_from FROM friends_requests WHERE user_id_to = $1)
`

func (q *Queries) GetIncomingFriendsRequests(ctx context.Context, userIDTo int64) ([]User, error) {
	rows, err := q.db.Query(ctx, getIncomingFriendsRequests, userIDTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Username, &i.PhotoUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWishlists = `-- name: GetWishlists :many
SELECT id, owner_id, title, description, is_private
FROM wishlists
WHERE owner_id = $1
`

func (q *Queries) GetWishlists(ctx context.Context, ownerID int64) ([]Wishlist, error) {
	rows, err := q.db.Query(ctx, getWishlists, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wishlist
	for rows.Next() {
		var i Wishlist
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
