// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendsRequest = `-- name: AcceptFriendsRequest :execrows
WITH deleted_request AS (
    DELETE FROM friends_requests
        WHERE user_id_to = $1 AND user_id_from = $2
        RETURNING user_id_to, user_id_from)
INSERT
INTO friends (user_id, friend_id)
SELECT user_id_from, user_id_to
FROM deleted_request
UNION ALL
SELECT user_id_to, user_id_from
FROM deleted_request
`

type AcceptFriendsRequestParams struct {
	UserIDTo   int64 `json:"user_id_to"`
	UserIDFrom int64 `json:"user_id_from"`
}

func (q *Queries) AcceptFriendsRequest(ctx context.Context, arg AcceptFriendsRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptFriendsRequest, arg.UserIDTo, arg.UserIDFrom)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelWishlistItemReservation = `-- name: CancelWishlistItemReservation :execrows
UPDATE wishlist_items
SET updated_at  = now(),
    reserved_by = NULL
WHERE wishlist_items.id = $1
  AND wishlist_items.reserved_by = $2
  AND EXISTS(SELECT id, created_at, updated_at, owner_id, title, description, is_private
             FROM wishlists
             WHERE wishlists.id = wishlist_items.wishlist_id
               AND EXISTS(SELECT user_id, friend_id, created_at from friends where friends.user_id = wishlists.owner_id AND friends.friend_id = $2)
               AND (wishlists.is_private = false OR
                    EXISTS(SELECT list_id, user_id, owner_id, created_at
                           FROM wishlist_access_list
                           WHERE wishlist_access_list.list_id = $1
                             AND wishlist_access_list.user_id = $2)))
`

type CancelWishlistItemReservationParams struct {
	ID         int64       `json:"id"`
	ReservedBy pgtype.Int8 `json:"reserved_by"`
}

func (q *Queries) CancelWishlistItemReservation(ctx context.Context, arg CancelWishlistItemReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelWishlistItemReservation, arg.ID, arg.ReservedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const checkIfFriends = `-- name: CheckIfFriends :one
SELECT count(*)
FROM friends
WHERE user_id = $1
  AND friend_id = $2
`

type CheckIfFriendsParams struct {
	UserID   int64 `json:"user_id"`
	FriendID int64 `json:"friend_id"`
}

func (q *Queries) CheckIfFriends(ctx context.Context, arg CheckIfFriendsParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkIfFriends, arg.UserID, arg.FriendID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkIfUserHasAccessToWishlist = `-- name: CheckIfUserHasAccessToWishlist :one
SELECT count(*)
FROM wishlists
WHERE wishlists.id = $1
  AND EXISTS(SELECT user_id, friend_id, created_at from friends where friends.user_id = wishlists.owner_id AND friends.friend_id = $2)
  AND (wishlists.is_private = false OR
       EXISTS(SELECT list_id, user_id, owner_id, created_at
              FROM wishlist_access_list
              WHERE wishlist_access_list.list_id = $1
                AND wishlist_access_list.user_id = $2))
`

type CheckIfUserHasAccessToWishlistParams struct {
	ID       int64 `json:"id"`
	FriendID int64 `json:"friend_id"`
}

func (q *Queries) CheckIfUserHasAccessToWishlist(ctx context.Context, arg CheckIfUserHasAccessToWishlistParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkIfUserHasAccessToWishlist, arg.ID, arg.FriendID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkUserHasAccessToPrivateWishlist = `-- name: CheckUserHasAccessToPrivateWishlist :one
SELECT list_id, user_id, owner_id, created_at
FROM wishlist_access_list
WHERE list_id = $1
  AND user_id = $2
`

type CheckUserHasAccessToPrivateWishlistParams struct {
	ListID int64 `json:"list_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CheckUserHasAccessToPrivateWishlist(ctx context.Context, arg CheckUserHasAccessToPrivateWishlistParams) (WishlistAccessList, error) {
	row := q.db.QueryRow(ctx, checkUserHasAccessToPrivateWishlist, arg.ListID, arg.UserID)
	var i WishlistAccessList
	err := row.Scan(
		&i.ListID,
		&i.UserID,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createFriendsRelationship = `-- name: CreateFriendsRelationship :execrows
INSERT INTO friends (user_id, friend_id)
VALUES ($1, $2),
       ($2, $1)
`

type CreateFriendsRelationshipParams struct {
	UserID   int64 `json:"user_id"`
	FriendID int64 `json:"friend_id"`
}

func (q *Queries) CreateFriendsRelationship(ctx context.Context, arg CreateFriendsRelationshipParams) (int64, error) {
	result, err := q.db.Exec(ctx, createFriendsRelationship, arg.UserID, arg.FriendID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createFriendsRequest = `-- name: CreateFriendsRequest :execrows
INSERT INTO friends_requests (user_id_from, user_id_to)
VALUES ($1, $2)
`

type CreateFriendsRequestParams struct {
	UserIDFrom int64 `json:"user_id_from"`
	UserIDTo   int64 `json:"user_id_to"`
}

func (q *Queries) CreateFriendsRequest(ctx context.Context, arg CreateFriendsRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, createFriendsRequest, arg.UserIDFrom, arg.UserIDTo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUser = `-- name: CreateUser :execrows
INSERT INTO users (id, username, name, photo_url)
VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Name     string `json:"name"`
	PhotoUrl string `json:"photo_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.PhotoUrl,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createWishlist = `-- name: CreateWishlist :one
INSERT INTO wishlists (owner_id, title, description, is_private)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, owner_id, title, description, is_private
`

type CreateWishlistParams struct {
	OwnerID     int64  `json:"owner_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	IsPrivate   bool   `json:"is_private"`
}

func (q *Queries) CreateWishlist(ctx context.Context, arg CreateWishlistParams) (Wishlist, error) {
	row := q.db.QueryRow(ctx, createWishlist,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.IsPrivate,
	)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.IsPrivate,
	)
	return i, err
}

const createWishlistItem = `-- name: CreateWishlistItem :one
INSERT INTO wishlist_items (wishlist_id, owner_id, title, description, price, links, reservable)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, owner_id, wishlist_id, title, description, price, links, reservable, reserved_by
`

type CreateWishlistItemParams struct {
	WishlistID  int64  `json:"wishlist_id"`
	OwnerID     int64  `json:"owner_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Price       string `json:"price"`
	Links       []byte `json:"links"`
	Reservable  bool   `json:"reservable"`
}

func (q *Queries) CreateWishlistItem(ctx context.Context, arg CreateWishlistItemParams) (WishlistItem, error) {
	row := q.db.QueryRow(ctx, createWishlistItem,
		arg.WishlistID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Links,
		arg.Reservable,
	)
	var i WishlistItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.WishlistID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Links,
		&i.Reservable,
		&i.ReservedBy,
	)
	return i, err
}

const deleteWishlist = `-- name: DeleteWishlist :execrows
DELETE
FROM wishlists
where id = $1
  and owner_id = $2
`

type DeleteWishlistParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) DeleteWishlist(ctx context.Context, arg DeleteWishlistParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWishlist, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWishlistAccessItem = `-- name: DeleteWishlistAccessItem :execrows
DELETE
from wishlist_access_list
WHERE list_id = $1
  AND user_id = $2
`

type DeleteWishlistAccessItemParams struct {
	ListID int64 `json:"list_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteWishlistAccessItem(ctx context.Context, arg DeleteWishlistAccessItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWishlistAccessItem, arg.ListID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWishlistAccessItems = `-- name: DeleteWishlistAccessItems :exec
DELETE
from wishlist_access_list
WHERE list_id = $1
`

func (q *Queries) DeleteWishlistAccessItems(ctx context.Context, listID int64) error {
	_, err := q.db.Exec(ctx, deleteWishlistAccessItems, listID)
	return err
}

const deleteWishlistItem = `-- name: DeleteWishlistItem :execrows
DELETE
FROM wishlist_items
WHERE id = $1
  and owner_id = $2
`

type DeleteWishlistItemParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) DeleteWishlistItem(ctx context.Context, arg DeleteWishlistItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWishlistItem, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const denyFriendsRequest = `-- name: DenyFriendsRequest :execrows
DELETE
FROM friends_requests
WHERE user_id_to = $1
  AND user_id_from = $2
`

type DenyFriendsRequestParams struct {
	UserIDTo   int64 `json:"user_id_to"`
	UserIDFrom int64 `json:"user_id_from"`
}

func (q *Queries) DenyFriendsRequest(ctx context.Context, arg DenyFriendsRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, denyFriendsRequest, arg.UserIDTo, arg.UserIDFrom)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFriendWishlistItems = `-- name: GetFriendWishlistItems :many
SELECT id, created_at, updated_at, owner_id, wishlist_id, title, description, price, links, reservable, reserved_by
FROM wishlist_items
WHERE wishlist_id = $1
  AND EXISTS(SELECT id, created_at, updated_at, owner_id, title, description, is_private
             FROM wishlists
             WHERE wishlists.id = $1
               AND EXISTS(SELECT user_id, friend_id, created_at from friends where friends.user_id = wishlists.owner_id AND friends.friend_id = $2)
               AND (wishlists.is_private = false OR
                    EXISTS(SELECT list_id, user_id, owner_id, created_at
                           FROM wishlist_access_list
                           WHERE wishlist_access_list.list_id = $1
                             AND wishlist_access_list.user_id = $2)))
`

type GetFriendWishlistItemsParams struct {
	WishlistID int64 `json:"wishlist_id"`
	FriendID   int64 `json:"friend_id"`
}

func (q *Queries) GetFriendWishlistItems(ctx context.Context, arg GetFriendWishlistItemsParams) ([]WishlistItem, error) {
	rows, err := q.db.Query(ctx, getFriendWishlistItems, arg.WishlistID, arg.FriendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WishlistItem
	for rows.Next() {
		var i WishlistItem
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.WishlistID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Links,
			&i.Reservable,
			&i.ReservedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendWishlists = `-- name: GetFriendWishlists :many
SELECT id, created_at, updated_at, owner_id, title, description, is_private
FROM wishlists
WHERE wishlists.owner_id = $1
  AND (is_private = false OR
       id IN (SELECT list_id FROM wishlist_access_list WHERE wishlist_access_list.owner_id = $1 AND wishlist_access_list.user_id = $2))
  AND EXISTS(SELECT user_id, friend_id, created_at from friends where friends.user_id = $1 AND friends.friend_id = $2)
`

type GetFriendWishlistsParams struct {
	OwnerID int64 `json:"owner_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) GetFriendWishlists(ctx context.Context, arg GetFriendWishlistsParams) ([]Wishlist, error) {
	rows, err := q.db.Query(ctx, getFriendWishlists, arg.OwnerID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wishlist
	for rows.Next() {
		var i Wishlist
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriends = `-- name: GetFriends :many
SELECT id, created_at, username, name, photo_url
FROM users
WHERE id IN (SELECT friend_id FROM friends WHERE user_id = $1)
`

func (q *Queries) GetFriends(ctx context.Context, userID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, getFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Username,
			&i.Name,
			&i.PhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncomingFriendsRequests = `-- name: GetIncomingFriendsRequests :many
SELECT id, created_at, username, name, photo_url
FROM users
WHERE id IN (SELECT user_id_from FROM friends_requests WHERE user_id_to = $1)
`

func (q *Queries) GetIncomingFriendsRequests(ctx context.Context, userIDTo int64) ([]User, error) {
	rows, err := q.db.Query(ctx, getIncomingFriendsRequests, userIDTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Username,
			&i.Name,
			&i.PhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncomingFriendsRequestsCount = `-- name: GetIncomingFriendsRequestsCount :one
SELECT count(*)
FROM friends_requests
WHERE user_id_to = $1
`

func (q *Queries) GetIncomingFriendsRequestsCount(ctx context.Context, userIDTo int64) (int64, error) {
	row := q.db.QueryRow(ctx, getIncomingFriendsRequestsCount, userIDTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOutcomingFriendsRequests = `-- name: GetOutcomingFriendsRequests :many
SELECT id, created_at, username, name, photo_url
FROM users
WHERE id IN (SELECT user_id_to FROM friends_requests WHERE user_id_from = $1)
`

func (q *Queries) GetOutcomingFriendsRequests(ctx context.Context, userIDFrom int64) ([]User, error) {
	rows, err := q.db.Query(ctx, getOutcomingFriendsRequests, userIDFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Username,
			&i.Name,
			&i.PhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, username, name, photo_url
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.Name,
		&i.PhotoUrl,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, username, name, photo_url
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.Name,
		&i.PhotoUrl,
	)
	return i, err
}

const getUserWishlists = `-- name: GetUserWishlists :many
SELECT id, created_at, updated_at, owner_id, title, description, is_private
FROM wishlists
WHERE owner_id = $1
`

func (q *Queries) GetUserWishlists(ctx context.Context, ownerID int64) ([]Wishlist, error) {
	rows, err := q.db.Query(ctx, getUserWishlists, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wishlist
	for rows.Next() {
		var i Wishlist
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWishlistAccessList = `-- name: GetWishlistAccessList :many
SELECT list_id, user_id, owner_id, created_at
FROM wishlist_access_list
WHERE list_id = $1
  AND owner_id = $2
`

type GetWishlistAccessListParams struct {
	ListID  int64 `json:"list_id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) GetWishlistAccessList(ctx context.Context, arg GetWishlistAccessListParams) ([]WishlistAccessList, error) {
	rows, err := q.db.Query(ctx, getWishlistAccessList, arg.ListID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WishlistAccessList
	for rows.Next() {
		var i WishlistAccessList
		if err := rows.Scan(
			&i.ListID,
			&i.UserID,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWishlistByWishId = `-- name: GetWishlistByWishId :one
SELECT id, created_at, updated_at, owner_id, title, description, is_private
FROM wishlists
WHERE wishlists.id = (SELECT wishlist_id FROM wishlist_items WHERE wishlist_items.id = $1)
`

func (q *Queries) GetWishlistByWishId(ctx context.Context, id int64) (Wishlist, error) {
	row := q.db.QueryRow(ctx, getWishlistByWishId, id)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.IsPrivate,
	)
	return i, err
}

const getWishlistItem = `-- name: GetWishlistItem :one
SELECT id, created_at, updated_at, owner_id, wishlist_id, title, description, price, links, reservable, reserved_by
FROM wishlist_items
WHERE id = $1
`

func (q *Queries) GetWishlistItem(ctx context.Context, id int64) (WishlistItem, error) {
	row := q.db.QueryRow(ctx, getWishlistItem, id)
	var i WishlistItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.WishlistID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Links,
		&i.Reservable,
		&i.ReservedBy,
	)
	return i, err
}

const getWishlistItems = `-- name: GetWishlistItems :many
SELECT id, created_at, updated_at, owner_id, wishlist_id, title, description, price, links, reservable, reserved_by
FROM wishlist_items
WHERE wishlist_id = $1
  and owner_id = $2
`

type GetWishlistItemsParams struct {
	WishlistID int64 `json:"wishlist_id"`
	OwnerID    int64 `json:"owner_id"`
}

func (q *Queries) GetWishlistItems(ctx context.Context, arg GetWishlistItemsParams) ([]WishlistItem, error) {
	rows, err := q.db.Query(ctx, getWishlistItems, arg.WishlistID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WishlistItem
	for rows.Next() {
		var i WishlistItem
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.WishlistID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Links,
			&i.Reservable,
			&i.ReservedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWishlistAccessItem = `-- name: InsertWishlistAccessItem :execrows
INSERT INTO wishlist_access_list (list_id, owner_id, user_id)
VALUES ($1, $2, $3)
`

type InsertWishlistAccessItemParams struct {
	ListID  int64 `json:"list_id"`
	OwnerID int64 `json:"owner_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) InsertWishlistAccessItem(ctx context.Context, arg InsertWishlistAccessItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWishlistAccessItem, arg.ListID, arg.OwnerID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveWishlistItem = `-- name: ReserveWishlistItem :execrows
UPDATE wishlist_items
SET updated_at  = now(),
    reserved_by = $2
WHERE wishlist_items.id = $1
  AND wishlist_items.reserved_by IS NULL
  AND EXISTS(SELECT id, created_at, updated_at, owner_id, title, description, is_private
             FROM wishlists
             WHERE wishlists.id = wishlist_items.wishlist_id
               AND EXISTS(SELECT user_id, friend_id, created_at from friends where friends.user_id = wishlists.owner_id AND friends.friend_id = $2)
               AND (wishlists.is_private = false OR
                    EXISTS(SELECT list_id, user_id, owner_id, created_at
                           FROM wishlist_access_list
                           WHERE wishlist_access_list.list_id = $1
                             AND wishlist_access_list.user_id = $2)))
`

type ReserveWishlistItemParams struct {
	ID         int64       `json:"id"`
	ReservedBy pgtype.Int8 `json:"reserved_by"`
}

func (q *Queries) ReserveWishlistItem(ctx context.Context, arg ReserveWishlistItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveWishlistItem, arg.ID, arg.ReservedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetWishlistItemReservation = `-- name: ResetWishlistItemReservation :execrows
UPDATE wishlist_items
SET updated_at  = now(),
    reserved_by = NULL
WHERE id = $1
`

func (q *Queries) ResetWishlistItemReservation(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, resetWishlistItemReservation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetWishlistItemsReservationsForFriend = `-- name: ResetWishlistItemsReservationsForFriend :execrows
UPDATE wishlist_items
SET updated_at  = now(),
    reserved_by = $2
WHERE owner_id = $1
`

type ResetWishlistItemsReservationsForFriendParams struct {
	OwnerID    int64       `json:"owner_id"`
	ReservedBy pgtype.Int8 `json:"reserved_by"`
}

func (q *Queries) ResetWishlistItemsReservationsForFriend(ctx context.Context, arg ResetWishlistItemsReservationsForFriendParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetWishlistItemsReservationsForFriend, arg.OwnerID, arg.ReservedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWishlist = `-- name: UpdateWishlist :one
UPDATE wishlists
SET updated_at  = now(),
    title       = $1,
    description = $2,
    is_private  = $3
WHERE id = $4
  and owner_id = $5
RETURNING id, created_at, updated_at, owner_id, title, description, is_private
`

type UpdateWishlistParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	IsPrivate   bool   `json:"is_private"`
	ID          int64  `json:"id"`
	OwnerID     int64  `json:"owner_id"`
}

func (q *Queries) UpdateWishlist(ctx context.Context, arg UpdateWishlistParams) (Wishlist, error) {
	row := q.db.QueryRow(ctx, updateWishlist,
		arg.Title,
		arg.Description,
		arg.IsPrivate,
		arg.ID,
		arg.OwnerID,
	)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.IsPrivate,
	)
	return i, err
}

const updateWishlistItem = `-- name: UpdateWishlistItem :one
UPDATE wishlist_items
SET updated_at  = now(),
    title       = $1,
    description = $2,
    price       = $3,
    links       = $4,
    reservable  = $5
WHERE id = $6
  AND owner_id = $7
RETURNING id, created_at, updated_at, owner_id, wishlist_id, title, description, price, links, reservable, reserved_by
`

type UpdateWishlistItemParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Price       string `json:"price"`
	Links       []byte `json:"links"`
	Reservable  bool   `json:"reservable"`
	ID          int64  `json:"id"`
	OwnerID     int64  `json:"owner_id"`
}

func (q *Queries) UpdateWishlistItem(ctx context.Context, arg UpdateWishlistItemParams) (WishlistItem, error) {
	row := q.db.QueryRow(ctx, updateWishlistItem,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Links,
		arg.Reservable,
		arg.ID,
		arg.OwnerID,
	)
	var i WishlistItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.WishlistID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Links,
		&i.Reservable,
		&i.ReservedBy,
	)
	return i, err
}
