global:
  scrape_interval: 15s # Time between standard metric collections

scrape_configs:
  - job_name: 'backend'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['backend:8080']