definitions:
  service.CreateWishlistItemRequest:
    properties:
      description:
        type: string
      links:
        items:
          $ref: '#/definitions/service.WishlistItemLink'
        type: array
      price:
        type: string
      reservable:
        type: boolean
      title:
        type: string
    type: object
  service.CreateWishlistRequest:
    properties:
      description:
        type: string
      is_private:
        type: boolean
      title:
        type: string
    type: object
  service.Friend:
    properties:
      id:
        type: integer
      name:
        type: string
      photo_url:
        type: string
      username:
        type: string
    type: object
  service.FriendWishlist:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
  service.Wishlist:
    properties:
      description:
        type: string
      id:
        type: integer
      is_private:
        type: boolean
      title:
        type: string
    type: object
  service.WishlistItem:
    properties:
      description:
        type: string
      id:
        type: integer
      links:
        items:
          $ref: '#/definitions/service.WishlistItemLink'
        type: array
      price:
        type: string
      reservable:
        type: boolean
      reserved_by:
        type: integer
      title:
        type: string
      wishlist_id:
        type: integer
    type: object
  service.WishlistItemLink:
    properties:
      title:
        type: string
      url:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Backend service for wishlists app
  title: Wishlists backend API
  version: "1.0"
paths:
  /api/user/friend/request/accept:
    post:
      parameters:
      - description: Friend ID
        in: query
        name: friend_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: accepts an incoming friend request
      tags:
      - Friends
  /api/user/friend/request/new:
    post:
      parameters:
      - description: Friend username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: creates a friend request to another user
      tags:
      - Friends
  /api/user/friend/wishlist/items:
    get:
      parameters:
      - description: Wishlist ID
        in: query
        name: wishlist_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.WishlistItem'
            type: array
      security:
      - ApiKeyAuth: []
      summary: returns wishlist items
      tags:
      - Friends
  /api/user/friend/wishlists:
    get:
      parameters:
      - description: Friend ID
        in: query
        name: friend_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.FriendWishlist'
            type: array
      security:
      - ApiKeyAuth: []
      summary: returns user's friend wishlists
      tags:
      - Friends
  /api/user/friends:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.Friend'
            type: array
      security:
      - ApiKeyAuth: []
      summary: returns user's friends list
      tags:
      - Friends
  /api/user/friends/requests/incoming:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.Friend'
            type: array
      security:
      - ApiKeyAuth: []
      summary: returns user's incoming friends requests
      tags:
      - Friends
  /api/user/wishlist:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: wishlist
        required: true
        schema:
          $ref: '#/definitions/service.CreateWishlistRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.Wishlist'
      security:
      - ApiKeyAuth: []
      summary: creates wishlist
      tags:
      - User
  /api/user/wishlist/item:
    get:
      parameters:
      - description: Wishlist item ID
        in: query
        name: item_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.WishlistItem'
      security:
      - ApiKeyAuth: []
      summary: returns wishlist item
      tags:
      - User
    post:
      consumes:
      - application/json
      parameters:
      - description: Wishlist ID
        in: query
        name: wishlist_id
        required: true
        type: integer
      - description: request body
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/service.CreateWishlistItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.WishlistItem'
      security:
      - ApiKeyAuth: []
      summary: creates a wishlist item
      tags:
      - User
  /api/user/wishlist/items:
    get:
      parameters:
      - description: Wishlist ID
        in: query
        name: wishlist_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.WishlistItem'
            type: array
      security:
      - ApiKeyAuth: []
      summary: returns wishlist items
      tags:
      - User
  /api/user/wishlists:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.Wishlist'
            type: array
      security:
      - ApiKeyAuth: []
      summary: returns user's wishlists
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
